# Use an official Ruby runtime as a parent image
FROM ruby:3.1.2

# Set environment variables for Rails
ENV RAILS_ENV=development

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    curl \
    postgresql-client \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up working directory
WORKDIR /myapp

# Copy Gemfile and Gemfile.lock to workdir
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

# Copy the entire project to the workdir
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the Rails server
CMD ["rails", "server", "-b", "0.0.0.0"]
