# Use an official Ruby runtime as a parent image
FROM ruby:3.1.2
FROM node:16 as build

# Set environment variables for Rails
ENV RAILS_ENV=production

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    curl \
    postgresql-client \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Verify Node.js installation
RUN node -v

# Set up working directory
WORKDIR /myapp

# Copy Gemfile and Gemfile.lock to workdir
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install --without development test

# Copy the entire project to the workdir
COPY . .

# Install npm dependencies
RUN npm install

# Update Browserslist database
RUN npx update-browserslist-db@latest

# Precompile assets
RUN bundle exec rake assets:precompile

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the Rails server
CMD ["rails", "server", "-b", "0.0.0.0"]
